### ISSUE TITLE
Dynamic Behaviour Missing 

### ISSUE THREAD

**Issue by andor201995** [Ramotion/expanding-collection-android#10]
I want to add images in the Background which are fetched from Server and render them on the background but as the mainbackground is only accepting integer value(i.e Resources ID) i am not able to use the feature as i saw the code you are in library converting ResourceID to bitmap . Please provide a method to send bitmap directly to the LIB.

**Comment by golovin47** [comment]
Hello, @andor201995. If you need this kind of feature, you're welcome to fork this lib and apply any customization you need.
