### ISSUE TITLE
UI Blocking when using remote images

### ISSUE THREAD

**Issue by oguzparlak** [Ramotion/expanding-collection-android#17]
There is a really bad transition when I toggle the card, I'm using Picasso to get the image from remote.
What should I do ? And I want to use Picasso caching not yours. Can I do that ?

**Comment by golovin47** [comment]
Hello, @oguzparlak. Picasso should have a callback for finish loading the image. You may need to fork this lib and customize it the way you need, i.e. run the animation on finish loading the image and to use Picasso cache.
