### ISSUE TITLE
Sometimes a card got a background that belongs to other card

### ISSUE THREAD

**Issue by t0mjoad** [Ramotion/expanding-collection-android#18]
Hello @RamotionDev, thanks for this awesome library. Very simple to use and  the result is very smoth and cool.

I got a problem with the cards, sometimes a card got a background that belongs to other card.

**VIDEO**

https://streamable.com/43zbj

As you can see, the first time I enter the city list everything is fine.
But when I enter again the same list (no changes are made in background): **City 2 and City 3** exchanged their backgrounds.

**ISSUE FLOW**
1. Enter _expanding collection activity_. Everything OK.
2. Go back to your main menu.
3. Re-enter again the _expanding collection activity_.
4. Error:
Card nº 1 got the background from card nº 3.
Card nº 3 got the background from card nº 5.
etc ....

**TEST**
I've checked both `setMainBackgroundResource()` and `setHeadBackgroundResource()` and they are being called properly.

In fact, my activity, card/comments classes and layouts are the ones from:
https://github.com/Ramotion/expanding-collection-android/tree/master/expanding-collection-full-example/src/main

**HARDWARE**

Issue happens on the 2 mobiles I tested:

- Nexus 5  (android 6.0.1)
- Xiaomi MiA1 (android 8.1.0)

Thanks for all!

**Comment by golovin47** [comment]
Hello, @t0mjoad. If you really made an absolute copy of example app, then you probably also copied getDataset() method from ExampleDataSet class. You should remove Collections.shuffle(dataset);
from your getDataSet() method.

**Comment by t0mjoad** [comment]
Hello @golovin47, thanks for your answer. I was able to solve it! 

In fact I forked your project and customized some things (lazy loading of images from URLs and corrected a pair of minor bugs). Don't know if you guys accept pull request but I can do it if you want.

Thanks!
