### ISSUE TITLE
Move to a card at specific position programmatically

### ISSUE THREAD

**Issue by modydevelops** [Ramotion/expanding-collection-android#27]
Hi, is there a way to move between pages using position programmatically?
I did try `.onPageSelected(int position)` but it didn't do it

**Comment by golovin47** [comment]
Hello, @modydevelops. Currently you can't switch pages programmatically, only using gesture. But you're welcome to fork this lib and add any feature you need.

**Comment by modydevelops** [comment]
@golovin47 thank you
If there’s a trick with .notifydatasetchange() please enlighten me because it works correctly the first time you call it then you have to manually swipe throw pages back and forth to see the dataset change effect. Thank you

**Comment by golovin47** [comment]
@modydevelops  You'd better look closer to ```ECPagerView.java```, especially to ```onPageSelected(int position)``` in it.
