### ISSUE TITLE
How do I download an Image from URL and set it as MainBackgroudResource and HeadBackroundResource?

### ISSUE THREAD

**Issue by Aravindraj93** [Ramotion/expanding-collection-android#29]
I am trying to implement this library in my project. I got stuck in loading the image from server to MainBackgroundResource and HeadBackgroudResource

**Comment by golovin47** [comment]
Hi, @Aravindraj93. Currently there is only one way of setting MainBackgroundResource and HeadBackgroudResource, which is using local resources. You can fork this lib and add any functionality you need.

**Comment by upendra-bajpai** [comment]
it's late but for others, I modified this library to do that.
https://github.com/upendra-bajpai/expanding-collection-network/
if you are having any difficulty you can file an issue there.
