### ISSUE TITLE
Update list

### ISSUE THREAD

**Issue by AliYusuf95** [Ramotion/expanding-collection-android#4]
When I try to update Dataset list nothing happen, even after calling `notifyDataSetChanged` from ECPagerViewAdapter.

**Comment by stovberpv** [comment]
Такая же проблема. Как заставить обновляться содержимое карточки при взаимодействии с объектами внутри неё? Нужно менять цвет текста при выборе позиции в списке. Но цвет меняется, только при сворачивании/разворачивании карточки. Адаптер никак не реагирует на notifyDataSetChanged().

**Comment by oleg-vasiliev** [comment]
Check out updated examples, simple-example module demostrates a simple way to change or remove items inside a card. Everything should work well. Maybe you make the mistake somewhere.
![image](https://user-images.githubusercontent.com/7147660/27083096-09d32a2e-5050-11e7-970c-5089cdd00a58.png)
