### ISSUE TITLE
Images From URL

### ISSUE THREAD

**Issue by rafael-alves-88** [Ramotion/expanding-collection-android#5]
Hi!

First I want to start saying this library is awesome!

Secondly, I would like to know how to use images downloaded from URL instead of fixed resources.

The methods from the interface forces us to use Integer as the image resource, and I would like to load the card and background images with Picasso like I can do with the person picture.

Is there any way to do this currently?

Thanks!

**Comment by Juriv** [comment]
Hey @rafael-alves-88 !
Thanks for using our lib, currently we don't support downloading images from URL, however we have this feature in pipeline.

**Comment by YogevUzan** [comment]
Any news regarding this feature??

**Comment by leolr02** [comment]
Any news fot that? the interface still needs the int  drawable resource  :(

**Comment by golovin47** [comment]
No such feature for now.

**Comment by upendra-bajpai** [comment]
it's late but for others, I modified this library to do that.
https://github.com/upendra-bajpai/expanding-collection-network/
if you are having any difficulty you can file an issue there.
