### ISSUE TITLE
customize  

### ISSUE THREAD

**Issue by smkazemi** [Ramotion/expanding-collection-android#8]
hello , tnx for share this .
i used Simple to create a card pager to my activity and have question .
i wanna put a Layout to Cards with out background ...
i know how to delete background and Header image but i don't know how to put my layout to cards .
how do it ?

**Comment by golovin47** [comment]
Hello, @smkazemi. You can add any view you want to head in instantiateCard() method. Look how it's done in example apps in this repository.
