### ISSUE TITLE
How to create use the background images from URL with the library?

### ISSUE THREAD

**Issue by saichandu415** [Ramotion/expanding-collection-android#9]
how to use URL with the library dynamically other than drawable resources?

**Comment by Sharathnasa** [comment]
@saichandu415 did you find a way to do this?

**Comment by saichandu415** [comment]
@Sharathnasa  No I didn't, Instead I created something simple of my own.

**Comment by Sharathnasa** [comment]
Ooh.. ok. Thank you.

**Comment by t0mjoad** [comment]
@saichandu415 Can you share that code with us? I need to do the same. Thanks!

**Comment by YogevUzan** [comment]
@saichandu415 Can you please share it with us ?

**Comment by YogevUzan** [comment]
@saichandu415 Mind to share it with us ?

**Comment by Gerrix90** [comment]
> @saichandu415 Mind to share it with us ?

I have adjusted code for images from url, you can try it
https://github.com/Gerrix90/expanding_collection_url_support

**Comment by golovin47** [comment]
Hello. Right now there is no such feature in this lib. You may fork it and apply any customization you need.
